repository_type: pipeline

pipeline_todos: false


lint:
  template_strings: False # "Jinja string found in" bin/create_regex.py and bin/seurat_qc.R
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - .github/CONTRIBUTING.md
    - .github/workflows/linting.yml
    - lib/NfcoreTemplate.groovy
