repository_type: pipeline

pipeline_todos: false

files_unchanged:
  - CODE_OF_CONDUCT.md
  - .github/CONTRIBUTING.md
  - .github/workflows/linting.yml
  - lib/NfcoreTemplate.groovy

lint:
  template_strings: False # "Jinja string found in" bin/create_regex.py and bin/seurat_qc.R
